# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1050, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tableWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1050, 21))
        self.menubar.setObjectName("menubar")
        self.menuCOM = QtWidgets.QMenu(self.menubar)
        self.menuCOM.setObjectName("menuCOM")
        self.menuBaseStation = QtWidgets.QMenu(self.menubar)
        self.menuBaseStation.setObjectName("menuBaseStation")
        self.menuRetranslate = QtWidgets.QMenu(self.menuBaseStation)
        self.menuRetranslate.setObjectName("menuRetranslate")
        MainWindow.setMenuBar(self.menubar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_retransEnable = QtWidgets.QAction(MainWindow)
        self.action_retransEnable.setObjectName("action_retransEnable")
        self.action_retransDisable = QtWidgets.QAction(MainWindow)
        self.action_retransDisable.setObjectName("action_retransDisable")
        self.action_currentTime = QtWidgets.QAction(MainWindow)
        self.action_currentTime.setObjectName("action_currentTime")
        self.action_periodTx = QtWidgets.QAction(MainWindow)
        self.action_periodTx.setObjectName("action_periodTx")
        self.action_numChannel = QtWidgets.QAction(MainWindow)
        self.action_numChannel.setObjectName("action_numChannel")
        self.action_powerTrans = QtWidgets.QAction(MainWindow)
        self.action_powerTrans.setObjectName("action_powerTrans")
        self.action_addrMod = QtWidgets.QAction(MainWindow)
        self.action_addrMod.setObjectName("action_addrMod")
        self.action_freqOffset = QtWidgets.QAction(MainWindow)
        self.action_freqOffset.setObjectName("action_freqOffset")
        self.action_validTable = QtWidgets.QAction(MainWindow)
        self.action_validTable.setObjectName("action_validTable")
        self.menuRetranslate.addAction(self.action_retransEnable)
        self.menuRetranslate.addAction(self.action_retransDisable)
        self.menuBaseStation.addAction(self.menuRetranslate.menuAction())
        self.menuBaseStation.addAction(self.action_currentTime)
        self.menuBaseStation.addAction(self.action_periodTx)
        self.menuBaseStation.addAction(self.action_numChannel)
        self.menuBaseStation.addAction(self.action_powerTrans)
        self.menuBaseStation.addAction(self.action_addrMod)
        self.menuBaseStation.addAction(self.action_freqOffset)
        self.menuBaseStation.addAction(self.action_validTable)
        self.menubar.addAction(self.menuCOM.menuAction())
        self.menubar.addAction(self.menuBaseStation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ПДУиТР - мод С"))
        self.menuCOM.setTitle(_translate("MainWindow", "COM-порт"))
        self.menuBaseStation.setTitle(_translate("MainWindow", "Базовая станция"))
        self.menuRetranslate.setTitle(_translate("MainWindow", "Режим ретранслятора"))
        self.action.setText(_translate("MainWindow", "Активировать"))
        self.action_2.setText(_translate("MainWindow", "Деактивировать"))
        self.action_retransEnable.setText(_translate("MainWindow", "Активировать"))
        self.action_retransDisable.setText(_translate("MainWindow", "Деактивировать"))
        self.action_currentTime.setText(_translate("MainWindow", "Корректировка времени"))
        self.action_periodTx.setText(_translate("MainWindow", "Время между передачей"))
        self.action_numChannel.setText(_translate("MainWindow", "Номер канала"))
        self.action_powerTrans.setText(_translate("MainWindow", "Мощность передатчика"))
        self.action_addrMod.setText(_translate("MainWindow", "Адрес модуляции"))
        self.action_freqOffset.setText(_translate("MainWindow", "Корректировка по частоте"))
        self.action_validTable.setText(_translate("MainWindow", "Таблица валидных номеров"))
